### ISSUE TITLE
Translated nav

### ISSUE THREAD

**Issue by sccmcca** [ultrabug/ultrabug.fr#2]
I noticed that the document headers and nav remain in English when French is the selected language. Is there a way to translate the headers and nav while keeping the ability to direct to the content in the selected language using this framework/theme?

**Comment by ultrabug** [comment]
Hi @scmcca 

The [mkdocs-static-i18n plugin does support navigation translation](https://github.com/ultrabug/mkdocs-static-i18n#translating-navigation) so that is achievable yes.

I'm not sure about which headers you're interested in to be translated, please give me more details?

**Comment by sccmcca** [comment]
Thanks for the link, I'll try it out.

For [example](https://github.com/ultrabug/ultrabug.fr/blob/master/docs/index.fr.md), the first header in the translated markdown files is the same as the [english](https://github.com/ultrabug/ultrabug.fr/blob/master/docs/index.md) one. I'm wondering if this is because of some indexing requirement?

**Comment by ultrabug** [comment]
Oh you mean the H1/H2/H3 # sections?

It's just me being lazy: when I translated the files I focused on the content and forgot to translate the headings! Nothing more :)
